### PR TITLE
Gradle build update

### PR DESCRIPTION
**Pull request by aalmiray**
This commit contains several updates:
- upgrade the build to Gradle 5.4
- update license headers
- configure build using http://aalmiray.github.io/kordamp-gradle-plugins/ (time saver ;-)
- configure publication to the Gradle Plugin Portal
- remove usage of metaclass for `remoteSession`
- add a `RemoteSession` task capable of handling `Closure` and `Action`.
- basic configuration for running CI on Travis

When making a release to the GPP, the recommended command is
    
    gradlew -Prelease=true publishPlugin

You may publish to Maven Central as well

    gradlew -Prelease=true publish

**NOTE**: read https://plugins.gradle.org/docs/submit before publishing to the GPP as you must register as plugin author an obtain a set of publication keys.

### CODE REVIEW

**Comment by aadamovich** [comment]
Hi @aalmiray! 

Release to GPP (`gradlew -Prelease=true publishPlugin`) and to Sonatype's snapshot repository (`gradlew publish`) works perfectly!

I have troubles publishing to Maven Central, though:

```
sshoogr-gradle>gradlew -Prelease=true publish
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Task :publishMainPublicationToSonatypeReleaseRepository FAILED
Could not transfer metadata com.aestasit.infrastructure.sshoogr:sshoogr-gradle:0.9.19-SNAPSHOT/maven-metadata10:11from/to remote (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Could not get resource 'com/aestasit/infrastructure/sshoogr/sshoogr-gradle/0.9.19-SNAPSHOT/maven-metadata.xml'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishMainPublicationToSonatypeReleaseRepository'.
> Failed to publish publication 'main' to repository 'sonatypeRelease'
   > Could not GET 'https://oss.sonatype.org/service/local/staging/deploy/maven2/com/aestasit/infrastructure/sshoogr/sshoogr-gradle/0.9.19-SNAPSHOT/maven-metadata.xml'. Received status code 400 from server: Bad Request

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 26s
10 actionable tasks: 5 executed, 5 up-to-date
```

Obviously, it is trying to upload snapshot to a release repo, which is not allowed. But what am I missing?

**Comment by aadamovich** [comment]
I have manually updated version to release (my muscle memory tells me I was doing that with release plugin before, but may be not for this project :) ). It works!

**Comment by aalmiray** [comment]
The current build setup does not automatically update the version number, even if `-Prelease=true` is given. You must manually move the version number to a non snapshot designation for now.

**Comment by aadamovich** [comment]
Yep, that was the problem. Artifact hit staging repository in Sonatype. But now I have some issues with POM validation.

image

**Comment by aadamovich** [comment]
For some reason build uploads 2 directories:

image

If I delete the second one, then I can push artifact to be released to maven central. @aalmiray Any advice here?

**Comment by aalmiray** [comment]
The second publication is need to resolve plugins using the 
`plugins` block instead of the `buildscript` block. It’s definitely required when publishing to the GPP. I’d still keep it if the intention is to allow plugin resolution from Maven Central even if the GPP is down.

**Comment by aadamovich** [comment]
Hmm, but why Sonatype complains about invalid pom for that second publication? Should I add something to the config of the project?

**Comment by aalmiray** [comment]
Does it? Hmm, I thought I fixed that problem with `0.19.0` https://github.com/aalmiray/kordamp-gradle-plugins/issues/116

If that pom is still missing info then you can skip it for now from Central. Unfortunately there's no current way to tell the general publication mechanism to skip this publication. I'll add this to the Kordamp suite.

**Pull request merged**
